import { Centre, QueueEntry, Slot, FarmerRecord, ProcurementRecord, AlertItem, AuditLogItem, DailyReport } from "./types";

export const MOCK_CENTRES: Centre[] = [
  {
    id: "6a9dbf0f2ff1af12c1d6ca69",
    code: "ABC-AMR-01",
    name: "ABC Procurement Centre",
    address: "Kotla Kalan, Amritsar, Punjab 143001",
    location: "Kotla Kalan, Amritsar",
    district: "Amritsar",
    state: "Punjab",
    status: "open",
    operating_hours: "08:00 AM – 05:00 PM",
    phone: "0183-2200100",
    default_slot_capacity: 20,
    max_daily_capacity: 140,
    weighbridge_count: 2,
    commodities: ["Wheat (Kanak)", "Paddy", "Mustard"],
    queue_count: 5,
    available_slots_today: 6,
  },
  {
    id: "centre-amritsar-north",
    code: "AMR-NORTH-02",
    name: "Majitha Grain Mandi",
    address: "Majitha Bypass, Amritsar, Punjab 143501",
    location: "Majitha, Amritsar",
    district: "Amritsar",
    state: "Punjab",
    status: "open",
    operating_hours: "08:00 AM – 06:00 PM",
    phone: "0183-2550200",
    default_slot_capacity: 25,
    max_daily_capacity: 175,
    weighbridge_count: 3,
    commodities: ["Wheat (Kanak)", "Paddy"],
    queue_count: 8,
    available_slots_today: 4,
  },
  {
    id: "centre-tarn-taran",
    code: "TT-CENTRAL-01",
    name: "Tarn Taran APMC Yard",
    address: "GT Road, Tarn Taran, Punjab 143401",
    location: "Tarn Taran",
    district: "Tarn Taran",
    state: "Punjab",
    status: "limited",
    operating_hours: "09:00 AM – 04:30 PM",
    phone: "0185-223344",
    default_slot_capacity: 15,
    max_daily_capacity: 105,
    weighbridge_count: 1,
    commodities: ["Wheat (Kanak)", "Basmati Paddy"],
    queue_count: 11,
    available_slots_today: 1,
  },
  {
    id: "centre-jalandhar-main",
    code: "JAL-MAIN-01",
    name: "Jalandhar Cantt Mandi",
    address: "Grain Market, Jalandhar Cantt, Punjab 144005",
    location: "Jalandhar",
    district: "Jalandhar",
    state: "Punjab",
    status: "open",
    operating_hours: "08:00 AM – 05:30 PM",
    phone: "0181-224455",
    default_slot_capacity: 30,
    max_daily_capacity: 210,
    weighbridge_count: 3,
    commodities: ["Wheat (Kanak)", "Paddy", "Maize"],
    queue_count: 14,
    available_slots_today: 7,
  },
];

export const MOCK_QUEUE_ENTRIES: QueueEntry[] = [
  {
    id: "q-1",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-1",
    queue_number: 1,
    token: "#01",
    farmer_name: "Gurpreet Singh",
    phone_masked: "98••••1042",
    slot_time: "08:00–09:00 AM",
    commodity: "Wheat (Kanak)",
    quantity: "45 quintals",
    status: "processing",
    arrived_at: "08:05 AM",
    processing_started_at: "08:12 AM",
    weighbridge_bay: "Weighbridge Bay 1",
  },
  {
    id: "q-2",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-2",
    queue_number: 2,
    token: "#02",
    farmer_name: "Harbhajan Mann",
    phone_masked: "94••••3311",
    slot_time: "08:00–09:00 AM",
    commodity: "Wheat (Kanak)",
    quantity: "60 quintals",
    status: "arrived",
    arrived_at: "08:18 AM",
    weighbridge_bay: "Weighbridge Bay 2",
  },
  {
    id: "q-3",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-3",
    queue_number: 3,
    token: "#03",
    farmer_name: "Balwinder Kaur",
    phone_masked: "97••••8821",
    slot_time: "09:00–10:00 AM",
    commodity: "Wheat (Kanak)",
    quantity: "35 quintals",
    status: "waiting",
  },
  {
    id: "q-4",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-4",
    queue_number: 4,
    token: "#04",
    farmer_name: "Jasbir Singh Dhillon",
    phone_masked: "98••••4412",
    slot_time: "09:00–10:00 AM",
    commodity: "Mustard",
    quantity: "28 quintals",
    status: "delayed",
    arrived_at: "08:45 AM",
    delay_reason: "High moisture reading (15.2%) — undergoing yard aeration",
  },
  {
    id: "q-5",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-5",
    queue_number: 5,
    token: "#05",
    farmer_name: "Manpreet Sandhu",
    phone_masked: "98••••9901",
    slot_time: "10:00–11:00 AM",
    commodity: "Wheat (Kanak)",
    quantity: "50 quintals",
    status: "waiting",
  },
  {
    id: "q-6",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    booking_id: "b-6",
    queue_number: 6,
    token: "#06",
    farmer_name: "Sukhwinder Cheema",
    phone_masked: "95••••7712",
    slot_time: "10:00–11:00 AM",
    commodity: "Wheat (Kanak)",
    quantity: "40 quintals",
    status: "completed",
    arrived_at: "07:45 AM",
    processing_started_at: "07:55 AM",
    completed_at: "08:12 AM",
    weighbridge_bay: "Weighbridge Bay 1",
  },
];

export const MOCK_SLOTS: Slot[] = [
  {
    id: "s-1",
    slot_ref: "SLT-0809",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "08:00",
    end_time: "09:00",
    time: "08:00–09:00 AM",
    capacity: 20,
    booked: 18,
    available: 2,
    status: "limited",
    commodity: "Wheat (Kanak)",
    is_closed: false,
  },
  {
    id: "s-2",
    slot_ref: "SLT-0910",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "09:00",
    end_time: "10:00",
    time: "09:00–10:00 AM",
    capacity: 20,
    booked: 20,
    available: 0,
    status: "full",
    commodity: "Wheat (Kanak)",
    is_closed: false,
  },
  {
    id: "s-3",
    slot_ref: "SLT-1011",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "10:00",
    end_time: "11:00",
    time: "10:00–11:00 AM",
    capacity: 20,
    booked: 12,
    available: 8,
    status: "available",
    commodity: "Wheat (Kanak)",
    is_closed: false,
  },
  {
    id: "s-4",
    slot_ref: "SLT-1112",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "11:00",
    end_time: "12:00",
    time: "11:00 AM–12:00 PM",
    capacity: 20,
    booked: 9,
    available: 11,
    status: "available",
    commodity: "Wheat (Kanak)",
    is_closed: false,
  },
  {
    id: "s-5",
    slot_ref: "SLT-1314",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "13:00",
    end_time: "14:00",
    time: "01:00–02:00 PM",
    capacity: 20,
    booked: 6,
    available: 14,
    status: "available",
    commodity: "Wheat (Kanak)",
    is_closed: false,
  },
  {
    id: "s-6",
    slot_ref: "SLT-1415",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    date: new Date().toISOString().split("T")[0],
    start_time: "14:00",
    end_time: "15:00",
    time: "02:00–03:00 PM",
    capacity: 20,
    booked: 0,
    available: 0,
    status: "closed",
    commodity: "Wheat (Kanak)",
    is_closed: true,
    note: "Yard cleaning & pesticide spray scheduled",
  },
];

export const MOCK_FARMERS: FarmerRecord[] = [
  {
    id: "f-1",
    farmer_reference: "F-10482",
    name: "Gurpreet Singh",
    phone: "+919876541042",
    phone_masked: "98••••1042",
    village: "Kotla Kalan",
    district: "Amritsar",
    state: "Punjab",
    land_area: "8.5 Acres",
    total_deliveries: 6,
    active_booking: {
      token: "#01",
      commodity: "Wheat (Kanak)",
      quantity: "45 quintals",
      slot_time: "08:00–09:00 AM",
      status: "processing",
    },
  },
  {
    id: "f-2",
    farmer_reference: "F-28910",
    name: "Harbhajan Mann",
    phone: "+919412343311",
    phone_masked: "94••••3311",
    village: "Manawala",
    district: "Amritsar",
    state: "Punjab",
    land_area: "12.0 Acres",
    total_deliveries: 11,
    active_booking: {
      token: "#02",
      commodity: "Wheat (Kanak)",
      quantity: "60 quintals",
      slot_time: "08:00–09:00 AM",
      status: "arrived",
    },
  },
  {
    id: "f-3",
    farmer_reference: "F-31124",
    name: "Balwinder Kaur",
    phone: "+919788118821",
    phone_masked: "97••••8821",
    village: "Jandiala Guru",
    district: "Amritsar",
    state: "Punjab",
    land_area: "5.0 Acres",
    total_deliveries: 4,
    active_booking: {
      token: "#03",
      commodity: "Wheat (Kanak)",
      quantity: "35 quintals",
      slot_time: "09:00–10:00 AM",
      status: "waiting",
    },
  },
  {
    id: "f-4",
    farmer_reference: "F-45501",
    name: "Jasbir Singh Dhillon",
    phone: "+919812444412",
    phone_masked: "98••••4412",
    village: "Chogawan",
    district: "Amritsar",
    state: "Punjab",
    land_area: "15.5 Acres",
    total_deliveries: 18,
    active_booking: {
      token: "#04",
      commodity: "Mustard",
      quantity: "28 quintals",
      slot_time: "09:00–10:00 AM",
      status: "delayed",
    },
  },
  {
    id: "f-5",
    farmer_reference: "F-59800",
    name: "Manpreet Sandhu",
    phone: "+919877669901",
    phone_masked: "98••••9901",
    village: "Verka",
    district: "Amritsar",
    state: "Punjab",
    land_area: "7.0 Acres",
    total_deliveries: 3,
    active_booking: {
      token: "#05",
      commodity: "Wheat (Kanak)",
      quantity: "50 quintals",
      slot_time: "10:00–11:00 AM",
      status: "waiting",
    },
  },
];

export const MOCK_PROCUREMENTS: ProcurementRecord[] = [
  {
    id: "proc-1",
    booking_id: "b-1",
    farmer_id: "f-1",
    farmer_name: "Gurpreet Singh",
    token: "#01",
    commodity: "Wheat (Kanak)",
    gross_weight_quintals: 62.4,
    tare_weight_quintals: 17.4,
    net_weight_quintals: 45.0,
    moisture_percent: 11.8,
    grade: "Grade A",
    msp_per_quintal: 2275,
    total_payout: 102375,
    weighbridge_bay: "Weighbridge Bay 1",
    status: "in_progress",
    started_at: "08:12 AM",
    history: [
      { timestamp: "08:05 AM", status: "arrived", staff_name: "Ramesh Kumar", note: "Vehicle verified at gate" },
      { timestamp: "08:12 AM", status: "in_progress", staff_name: "Suresh Pal", note: "Gross weighing completed on Bay 1" },
    ],
  },
  {
    id: "proc-6",
    booking_id: "b-6",
    farmer_id: "f-6",
    farmer_name: "Sukhwinder Cheema",
    token: "#06",
    commodity: "Wheat (Kanak)",
    gross_weight_quintals: 56.8,
    tare_weight_quintals: 16.8,
    net_weight_quintals: 40.0,
    moisture_percent: 11.2,
    grade: "Grade A",
    msp_per_quintal: 2275,
    total_payout: 91000,
    weighbridge_bay: "Weighbridge Bay 1",
    status: "completed",
    started_at: "07:55 AM",
    completed_at: "08:12 AM",
    history: [
      { timestamp: "07:45 AM", status: "arrived", staff_name: "Ramesh Kumar" },
      { timestamp: "07:55 AM", status: "in_progress", staff_name: "Suresh Pal" },
      { timestamp: "08:05 AM", status: "verification", staff_name: "Dr. Sandhu (Quality Assessor)" },
      { timestamp: "08:12 AM", status: "completed", staff_name: "Suresh Pal", note: "Settlement receipt KS-RCP-8802 generated" },
    ],
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alt-1",
    title: "Light Rain Expected in Majitha & Verka",
    message: "District meteorological warning: Scattered drizzle expected after 03:00 PM. Covered sheds are fully prepared.",
    severity: "warning",
    type: "weather",
    created_at: "07:30 AM",
    is_active: true,
  },
  {
    id: "alt-2",
    title: "Weighbridge Bay 2 Calibration Completed",
    message: "Weights & Measures inspector verified 100% calibration accuracy on Weighbridge Bay 2.",
    severity: "info",
    type: "operational",
    created_at: "08:00 AM",
    is_active: true,
  },
  {
    id: "alt-3",
    title: "MSP Payout Cycle 4 Processing Successfully",
    message: "Punjab State Civil Supplies Corporation has initiated DBT transfers for 142 farmers.",
    severity: "info",
    type: "operational",
    created_at: "Yesterday",
    is_active: true,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud-1",
    actor_name: "Suresh Pal (Weighbridge Incharge)",
    actor_id: "s-1",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    action: "STATUS_TRANSITION",
    details: "Called Token #01 (Gurpreet Singh) to Weighbridge Bay 1",
    entity_type: "queue",
    entity_id: "q-1",
    time_ist: "08:12 AM",
  },
  {
    id: "aud-2",
    actor_name: "Dr. H.S. Sandhu (Quality Officer)",
    actor_id: "s-2",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    action: "MOISTURE_TEST",
    details: "Recorded 15.2% moisture for Token #04; marked Delayed for aeration",
    entity_type: "procurement",
    entity_id: "proc-4",
    time_ist: "08:48 AM",
  },
  {
    id: "aud-3",
    actor_name: "Ramesh Kumar (Gate Clerk)",
    actor_id: "s-3",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    action: "ARRIVED_CHECKIN",
    details: "Verified Passbook and checked in Harbhajan Mann (Token #02)",
    entity_type: "queue",
    entity_id: "q-2",
    time_ist: "08:18 AM",
  },
  {
    id: "aud-4",
    actor_name: "Jagjit Singh (Mandi Supervisor)",
    actor_id: "s-4",
    centre_id: "6a9dbf0f2ff1af12c1d6ca69",
    action: "SLOT_CAPACITY_CHANGE",
    details: "Closed Slot 02:00–03:00 PM for scheduled yard treatment",
    entity_type: "slot",
    entity_id: "s-6",
    time_ist: "Yesterday",
  },
];

export const MOCK_DAILY_REPORT: DailyReport = {
  date: new Date().toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }),
  centre_name: "ABC Procurement Centre",
  total_farmers_served: 42,
  total_procured_quintals: 1845.5,
  total_msp_disbursed: 4198512,
  breakdown_by_crop: {
    "Wheat (Kanak)": 1520.0,
    "Mustard": 185.5,
    "Paddy": 140.0,
  },
  average_wait_minutes: 14.5,
  weighbridge_utilization_pct: 86.4,
};
